### ISSUE TITLE
Traceback问题🤔

### ISSUE THREAD

**Issue by specked2527** [JoeanAmier/XHS-Downloader#115]
Traceback
```py
>x -u “http://xhslink.com/EgyKEO”                            开始处理作品：https://www.xiaohongshu.com/discovery/item/66842a72000000000a004343
文件 Onlyoneprivate_2024-07-03_00.27.30_Kula_Diamond_2.png 下载成功
文件 Onlyoneprivate_2024-07-03_00.27.30_Kula_Diamond_3.png 下载成功
文件 Onlyoneprivate_2024-07-03_00.27.30_Kula_Diamond_1.png 下载成功
Traceback (most recent call last):
  File "main.py", line 79, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "source\CLI\main.py", line 204, in cli
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 687, in run_until_complete
  File "source\CLI\main.py", line 202, in main
  File "source\CLI\main.py", line 62, in run
  File "source\application\app.py", line 184, in extract_cli
  File "source\application\app.py", line 221, in __deal_extract
  File "source\application\app.py", line 144, in __download_files
  File "source\application\app.py", line 150, in save_data
  File "source\module\recorder.py", line 92, in add
  File "aiosqlite\core.py", line 193, in execute
  File "aiosqlite\core.py", line 132, in _execute
  File "aiosqlite\core.py", line 115, in run
sqlite3.OperationalError: table explore_data has no column named 动图地址
[12136] Failed to execute script 'main' due to unhandled exception!
```

**Comment by JoeanAmier** [comment]
把旧的数据库文件删掉。
