### ISSUE TITLE
解析提示这个 什么问题呢

### ISSUE THREAD

**Issue by kiko923** [JoeanAmier/XHS-Downloader#127]
开始处理作品：https://www.xiaohongshu.com/discovery/item/669c868f0000000025016445
Error handling request
Traceback (most recent call last):
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\deskop\XHS-Downloader-master\source\application\app.py", line 308, in handle
    if data := await self.__deal_extract(url[0], download, index, None, None, not skip, ):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\deskop\XHS-Downloader-master\source\application\app.py", line 191, in __deal_extract
    namespace = self.__generate_data_object(html)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\deskop\XHS-Downloader-master\source\application\app.py", line 217, in __generate_data_object
    data = self.convert.run(html)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\deskop\XHS-Downloader-master\source\expansion\converter.py", line 20, in run
    self.__convert_object(
  File "D:\User\deskop\XHS-Downloader-master\source\expansion\converter.py", line 31, in __convert_object
    return safe_load(text.lstrip("window.__INITIAL_STATE__="))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yionhci\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 23, column 29:
                return { columns: 5, gapV: 16, gapH: 32, columnW ...

**Comment by Flionay** [comment]
我遇到了同样的问题

**Comment by JoeanAmier** [comment]
小红书网页限制更新了，最新源码已处理。
