### ISSUE TITLE
源码运行报错，源码运行出现以下错误，请问是什么原因？

### ISSUE THREAD

**Issue by uaaazcc** [JoeanAmier/XHS-Downloader#192]
`PS G:\XHS-Downloader-master\XHS-Downloader-master> python main.py

Traceback (most recent call last):

  File "G:\XHS-Downloader-master\XHS-Downloader-master\main.py", line 6, in <module>
    from source import Settings

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\__init__.py", line 1, in <module>
    from .CLI import cli

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\CLI\__init__.py", line 1, in <module>
    from .main import cli

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\CLI\main.py", line 19, in <module>
    from source.application import XHS

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\application\__init__.py", line 1, in <module>
    from .app import XHS

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\application\app.py", line 24, in <module>
    from source.module import DataRecorder

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\module\__init__.py", line 2, in <module>
    from .manager import Manager

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\module\manager.py", line 15, in <module>
    from .static import HEADERS

  File "G:\XHS-Downloader-master\XHS-Downloader-master\source\module\static.py", line 7
    PROJECT = f"XHS-Downloader V{VERSION_MAJOR}.{
              ^
SyntaxError: unterminated string literal (detected at line 7)`

**Comment by 0zcl** [comment]
也遇到了

**Comment by 0zcl** [comment]
readme源码运行，第4点：运行 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt 命令安装程序所需模块

**Comment by shirubei** [comment]
这个问题其实是代码写的不规范（或许python版本变化导致的错误？）：f-string中换行导致了编译器人物字符串没有正确结束
可以改成这样：
PROJECT = f"XHS-Downloader V{VERSION_MAJOR}.{VERSION_MINOR} {'Beta' if VERSION_BETA else 'Stable'}"
