### ISSUE TITLE
SyntaxError: unterminated string literal (detected at line 28)

### ISSUE THREAD

**Issue by BingyuanZhang** [JoeanAmier/XHS-Downloader#91]
Traceback (most recent call last):
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/main.py", line 4, in <module>
    from source import XHS
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/__init__.py", line 1, in <module>
    from .CLI import cli
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/CLI/__init__.py", line 1, in <module>
    from .main import cli
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/CLI/main.py", line 19, in <module>
    from source.application import XHS
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/application/__init__.py", line 1, in <module>
    from .app import XHS
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/application/app.py", line 17, in <module>
    from source.module import DataRecorder
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/module/__init__.py", line 2, in <module>
    from .manager import Manager
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/module/manager.py", line 11, in <module>
    from .static import HEADERS
  File "/Users/bingyuanzhang/Desktop/vf/xhs/XHS-Downloader/source/module/static.py", line 28
    PROJECT = f"XHS-Downloader V{VERSION_MAJOR}.{

我用的是3.12的python

**Comment by JoeanAmier** [comment]
报错不完整。

**Comment by BingyuanZhang** [comment]
就是直接python main.py就报这个错了

> 报错不完整。

就是直接python main.py就报这个错了

**Comment by JoeanAmier** [comment]
确保运行代码的 Python 解释器路径及版本无误。

**Comment by haohaoOwO** [comment]
你好 我也出现了相同情况 请问你的问题解决了吗

**Comment by haohaoOwO** [comment]
/(ㄒoㄒ)/~~
